name: Check build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  clippy_check:
    name: Run clippy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run lints
        run: >-
          cargo clippy --all-targets --all-features --
          -D clippy::correctness
          -D clippy::suspicious_map
          -D clippy::suspicious_unary_op_formatting
          -D clippy::swap_ptr_to_ref
          -D clippy::drop_non_drop
          -D clippy::empty_loop
          -D clippy::iter_out_of_bounds
          -D clippy::lines_filter_map_ok
          -D clippy::multi_assignments
          -D clippy::boxed_local
          -D clippy::cmp_owned
          -D clippy::drain_collect
          -D clippy::expect_fun_call
          -D clippy::extend_with_drain
          -D clippy::format_collect
          -D clippy::iter_nth
          -D clippy::iter_overeager_cloned
          -D clippy::large_enum_variant
          -D clippy::manual_memcpy
          -D clippy::useless_vec
          -D clippy::vec_init_then_push
          -D clippy::slow_vector_initialization
          -D clippy::assertions_on_constants
          -D clippy::assign_op_pattern
          -D clippy::blocks_in_if_conditions
          -D clippy::bool_assert_comparison
          -D clippy::borrow_interior_mutable_const
          -D clippy::builtin_type_shadow
          -D clippy::chars_last_cmp
          -D clippy::collapsible_else_if
          -D clippy::collapsible_if
          -D clippy::collapsible_match
          -D clippy::comparison_chain
          -D clippy::comparison_to_empty
          -D clippy::double_must_use
          -D clippy::double_neg
          -D clippy::duplicate_underscore_argument
          -D clippy::enum_variant_names
          -D clippy::excessive_precision
          -D clippy::field_reassign_with_default
          -D clippy::filter_map_bool_then
          -D clippy::fn_to_numeric_cast
          -D clippy::for_kv_map
          -D clippy::implicit_saturating_add
          -D clippy::implicit_saturating_sub
          -D clippy::infallible_destructuring_match
          -D clippy::init_numbered_fields
          -D clippy::into_iter_on_ref
          -D clippy::just_underscores_and_digits
          -D clippy::len_zero
          -D clippy::let_and_return
          -D clippy::let_unit_value
          -D clippy::main_recursion
          -D clippy::manual_bits
          -D clippy::manual_is_finite
          -D clippy::manual_map
          -D clippy::manual_saturating_arithmetic
          -D clippy::manual_range_contains
          -D clippy::match_overlapping_arm
          -D clippy::match_ref_pats
          -D clippy::match_result_ok
          -D clippy::mem_replace_option_with_none
          -D clippy::missing_safety_doc
          -D clippy::mixed_case_hex_literals
          -D clippy::module_inception
          -D clippy::must_use_unit
          -D clippy::needless_borrow
          -D clippy::needless_else
          -D clippy::needless_late_init
          -D clippy::needless_parens_on_range_literals
          -D clippy::needless_range_loop
          -D clippy::needless_return
          -D clippy::needless_return_with_question_mark
          -D clippy::neg_multiply
          -D clippy::new_ret_no_self
          -D clippy::obfuscated_if_else
          -D clippy::ok_expect
          -D clippy::print_literal
          -D clippy::question_mark
          -D clippy::redundant_closure
          -D clippy::redundant_field_names
          -D clippy::unnecessary_fold
          -D clippy::unnecessary_fallible_conversions
          -D clippy::trim_split_whitespace
          -D clippy::unused_unit
          -D clippy::while_let_on_iterator
          -D clippy::zero_ptr
          -D clippy::unnecessary_owned_empty_strings
          -D clippy::unnecessary_mut_passed
          -D clippy::unnecessary_lazy_evaluations
          -D clippy::if_not_else
          -D clippy::implicit_clone
          -D clippy::manual_assert
          -D clippy::mut-mut
          -D clippy::match_bool
          -D clippy::ref_binding_to_reference
          -D clippy::ref_option_ref
          -W clippy::too_many_lines
          -D clippy::unnecessary_wraps
          -W clippy::cognitive_complexity
          -D clippy::manual_clamp
          -D clippy::option_if_let_else
          -W clippy::panic
          -D clippy::panic_in_result_fn